services:
  lothal.api.gateway:
    image: ${DOCKER_REGISTRY-}lothalapigateway
    build:
      context: .
      dockerfile: Dockerfile.ApiGateway
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5024:8080"
    depends_on:
      - basket-api

  basket-api:
    image: ${DOCKER_REGISTRY-}lothalbasketapi
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      replicas: 2
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Host=basket-db;Database=BasketDb;Username=postgres;Password=postgres
      - Nats__Url=nats:4222
    depends_on:
      - basket-db
      - nats

  lothal.basket.consumer:
    image: ${DOCKER_REGISTRY-}lothalbasketconsumer
    build:
      context: .
      dockerfile: Dockerfile.Consumer
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Nats__Url=nats:4222
      - Couchbase__ConnectionString=couchbase://couchbase
      - Couchbase__Username=Administrator
      - Couchbase__Password=password
    depends_on:
      - nats
      - couchbase

  basket-db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=BasketDb
    ports:
      - "5432:5432"
    volumes:
      - basket_db_data:/var/lib/postgresql/data

  nats:
    image: nats:latest
    ports:
      - "4222:4222"
      - "8222:8222"

  couchbase:
    image: couchbase:community-7.6.2
    environment:
      - CB_USERNAME=Administrator
      - CB_PASSWORD=password
    ports:
      - "8091-8096:8091-8096"
      - "11210-11211:11210-11211"
    volumes:
      - couchbase_data:/opt/couchbase/var

volumes:
  basket_db_data:
  couchbase_data:
