FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
USER app
WORKDIR /app
EXPOSE 8080

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src

# Copy csproj file
COPY ["src/ApiGateway/Lothal.ApiGateway.csproj", "src/ApiGateway/"]

# Restore dependencies
RUN dotnet restore "./src/ApiGateway/Lothal.ApiGateway.csproj"

# Copy the rest of the source code
COPY . .
WORKDIR "/src/src/ApiGateway"
RUN dotnet build "./Lothal.ApiGateway.csproj" -c $BUILD_CONFIGURATION -o /app/build

FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "./Lothal.ApiGateway.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Lothal.ApiGateway.dll"]
