services:
  lothal.api.gateway:
    image: ${DOCKER_REGISTRY-}lothalapigateway
    build:
      context: .
      dockerfile: Dockerfile.ApiGateway
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5024:8080"
    depends_on:
      - lothal.basket.service

  lothal.basket.service:
    image: ${DOCKER_REGISTRY-}lothalbasketservice
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      replicas: 2
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=basket-db;Database=BasketDb;Username=postgres;Password=postgres
    depends_on:
      - basket-db

  basket-db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=BasketDb
    ports:
      - "5432:5432"
    volumes:
      - basket_db_data:/var/lib/postgresql/data

volumes:
  basket_db_data:
