<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-Lothal.Basket.Consumer-c79795f9-af01-48e7-83c0-31b1b58a377e</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Couchbase.Extensions.DependencyInjection" Version="3.9.0" />
    <PackageReference Include="CouchbaseNetClient" Version="3.9.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.0" />
    <PackageReference Include="NATS.Net" Version="2.7.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\BuildingBlocks\Lothal.BuildingBlocks\Lothal.BuildingBlocks.csproj" />
  </ItemGroup>
</Project>
