<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Lothal.Basket.Domain\Lothal.Basket.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Lothal.Mediator" Version="1.0.0" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
